# Blog posts
from datetime import datetime

post_data = [{
    "theme": 1,
    "title": "Phang Nga Bay: a day in paradise",
    "author_id": 5,
    "date_submitted": datetime.strptime("2023-01-01 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-01 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_01.jpg",
    "picture_v_source": "https://pixabay.com/photos/phang-nga-bay-phuket-province-2076833/",
    "picture_s": "Picture_s_01.jpg",
    "picture_s_source": "https://pixabay.com/photos/mountains-tropical-thailand-2129544/",
    "picture_h": "Picture_h_01.jpg",
    "picture_h_source": "https://pixabay.com/photos/thailand-phang-nga-bay-beach-sea-180828/",
    "picture_alt": "Phang Nga Bay",
    },
    {
    "theme": 1,
    "title": "A waterfall trail in the Californian Coast is what you need right now",
    "author_id": 6,
    "date_submitted": datetime.strptime("2023-01-11 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-11 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_02.jpg",
    "picture_v_source": "https://pixabay.com/photos/beach-waterfall-coastal-california-1630472/",
    "picture_s": "Picture_s_02.jpg",
    "picture_s_source": "https://pixabay.com/photos/beach-waterfall-sea-nature-1630475/",
    "picture_h": "Picture_h_02.jpg",
    "picture_h_source": "https://pixabay.com/photos/san-francisco-california-beach-4271367/",
    "picture_alt": "Californian Coast",
    },
    {
    "theme": 1,
    "title": "What brought me to Cape Town's Boulder Beach in 2022",
    "author_id": 7,
    "date_submitted": datetime.strptime("2023-01-16 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-17 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_03.jpg",
    "picture_v_source": "https://pixabay.com/photos/cape-town-boulder-beach-penguin-5741110/",
    "picture_s": "Picture_s_03.jpg",
    "picture_s_source": "https://pixabay.com/photos/penguins-birds-animals-3994532/",
    "picture_h": "Picture_h_03.jpg",
    "picture_h_source": "https://pixabay.com/photos/cape-town-boulder-beach-penguin-5741110/",
    "picture_alt": "Boulder Beach",
    },
    {
    "theme": 2,
    "title": "The ancient city of Dubrovnik is a stunner",
    "author_id": 7,
    "date_submitted": datetime.strptime("2023-01-17 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-17 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_04.jpg",
    "picture_v_source": "https://pixabay.com/photos/buildings-street-dubrovnik-croatia-4352262/",
    "picture_s": "Picture_s_04.jpg",
    "picture_s_source": "https://pixabay.com/photos/dubrovnik-croatia-adriatic-red-5100607/",
    "picture_h": "Picture_h_04.jpg",
    "picture_h_source": "https://pixabay.com/photos/dubrovnik-croatia-kings-landing-512798/",
    "picture_alt": "Dubrovnik",
    },
    {
    "theme": 4,
    "title": "Petra is the way Jordan reminds the world of the roots of civilization",
    "author_id": 5,
    "date_submitted": datetime.strptime("2023-01-18 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-18 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_05.jpg",
    "picture_v_source": "https://pixabay.com/photos/canyon-landmark-petra-jordan-4358577/",
    "picture_s": "Picture_s_05.jpg",
    "picture_s_source": "https://pixabay.com/photos/jordan-petra-holiday-middle-east-181912/",
    "picture_h": "Picture_h_05.jpg",
    "picture_h_source": "https://pixabay.com/photos/petra-jordan-travel-world-heritage-3839666/",
    "picture_alt": "Petra",
    },
    {
    "theme": 2,
    "title": "And I quote 'half of my heart is in Havana, ooh na-na",
    "author_id": 7,
    "date_submitted": datetime.strptime("2023-01-19 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-19 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_06.jpg",
    "picture_v_source": "https://pixabay.com/photos/cyprus-limassol-old-town-old-house-2638534/",
    "picture_s": "Picture_s_06.jpg",
    "picture_s_source": "https://pixabay.com/photos/cars-old-car-vehicle-cuba-oltimer-1638594/",
    "picture_h": "Picture_h_06.jpg",
    "picture_h_source": "https://pixabay.com/photos/havana-cuba-city-urban-sea-wharf-4027210/",
    "picture_alt": "Havana",
    },
    {
    "theme": 4,
    "title": "The Cambodian trip to renew your energies and clean your soul",
    "author_id": 5,
    "date_submitted": datetime.strptime("2023-01-20 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-21 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_07.jpg",
    "picture_v_source": "https://pixabay.com/photos/angkor-thom-angkor-wat-cambodia-1349581/",
    "picture_s": "Picture_s_07.jpg",
    "picture_s_source": "https://pixabay.com/photos/angkor-wat-temple-amazing-934094/",
    "picture_h": "Picture_h_07.jpg",
    "picture_h_source": "https://pixabay.com/photos/buddhism-asia-boys-cambodia-1822518/",
    "picture_alt": "Cambodja",
    },
    {
    "theme": 3,
    "title": "Kenya is perfect for that Safari you had in mind",
    "author_id": 6,
    "date_submitted": datetime.strptime("2023-01-20 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-21 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_08.jpg",
    "picture_v_source": "https://pixabay.com/photos/cheetahs-animals-safari-5689873/",
    "picture_s": "Picture_s_08.jpg",
    "picture_s_source": "https://pixabay.com/photos/safari-africa-tree-piste-kenya-1029078/",
    "picture_h": "Picture_h_08.jpg",
    "picture_h_source": "https://pixabay.com/photos/africa-kenya-safari-wildlife-4058720/",
    "picture_alt": "Kenya safari",
    },
    {
    "theme": 3,
    "title": "The Andes like you've never seen before: a spetacular setting",
    "author_id": 6,
    "picture_v": "Picture_v_09.jpg",
    "date_submitted": datetime.strptime("2023-01-20 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-21 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v_source": "https://pixabay.com/photos/patagonia-argentina-landscape-5173688/",
    "picture_s": "Picture_s_09.jpg",
    "picture_s_source": "https://pixabay.com/photos/pink-flamingos-birds-lake-nature-6558751/",
    "picture_h": "Picture_h_09.jpg",
    "picture_h_source": "https://pixabay.com/photos/lama-ecuador-cotopaxi-91978/",
    "picture_alt": "Andes in Ecuador",
    },
    {
    "theme": 3,
    "title": "Touring the Rio Negro is not for the faint of heart",
    "author_id": 6,
    "date_submitted": datetime.strptime("2023-01-22 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-22 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_10.jpg",
    "picture_v_source": "https://pixabay.com/photos/jaguar-panther-zoo-safari-nature-7393553/",
    "picture_s": "Picture_s_10.jpg",
    "picture_s_source": "https://pixabay.com/photos/amazon-forest-nature-trees-outdoor-4769367/",
    "picture_h": "Picture_h_10.jpg",
    "picture_h_source": "https://pixabay.com/photos/brazil-rainforest-amazon-rio-negro-69588/",
    "picture_alt": "Amazon forest",
    },
    {
    "theme": 2,
    "title": "Tokio is where the ultramodern and the traditional mix under the opulent Mount Fuji",
    "author_id": 7,
    "date_submitted": datetime.strptime("2023-01-24 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-25 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_11.jpg",
    "picture_v_source": "https://pixabay.com/photos/boat-cherry-blossom-park-river-1835081/",
    "picture_s": "Picture_s_11.jpg",
    "picture_s_source": "https://pixabay.com/photos/tokyo-japan-shibuya-night-4807294/",
    "picture_h": "Picture_h_11.jpg",
    "picture_h_source": "https://pixabay.com/photos/tokyo-japan-city-asia-fuji-urban-4358758/",
    "picture_alt": "Tokio",
    },
    {
    "theme": 4,
    "title": "I've been to the 'Land of Kings' and this is what I learned - a girl in Rajasthan",
    "author_id": 5,
    "date_submitted": datetime.strptime("2023-01-24 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-25 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_12.jpg",
    "picture_v_source": "https://pixabay.com/photos/architecture-chomu-palace-rajasthan-639103/",
    "picture_s": "Picture_s_12.jpg",
    "picture_s_source": "https://pixabay.com/photos/india-rajastan-strong-amber-1457098/",
    "picture_h": "Picture_h_12.jpg",
    "picture_h_source": "https://pixabay.com/photos/india-rajastan-jaisalmer-palace-919195/",
    "picture_alt": "Rajasthan",
    },
    {
    "theme": 4,
    "title": "Egypt: travelling in time",
    "author_id": 5,
    "date_submitted": datetime.strptime("2023-01-27 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-27 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_13.jpg",
    "picture_v_source": "https://pixabay.com/photos/temple-architecture-buildings-4687909/",
    "picture_s": "Picture_s_13.jpg",
    "picture_s_source": "https://pixabay.com/photos/hieroglyphs-pharaohs-egypt-luxor-429863/",
    "picture_h": "Picture_h_13.jpg",
    "picture_h_source": "https://pixabay.com/photos/egypt-desert-egyptian-temple-giza-1179193/",
    "picture_alt": "Egypt",
    },
    {
    "theme": 2,
    "title": "Digital nomads should check out these Budapest coffee shops",
    "author_id": 5,
    "date_submitted": datetime.strptime("2023-01-30 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-30 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_14.jpg",
    "picture_v_source": "https://pixabay.com/photos/scape-budapest-parliament-92603/",
    "picture_s": "Picture_s_14.jpg",
    "picture_s_source": "https://pixabay.com/photos/budapest-hungary-632851/",
    "picture_h": "Picture_b_14.jpg",
    "picture_h_source": "https://pixabay.com/photos/matthias-church-church-night-lights-4516471/",
    "picture_alt": "Budapest",
    }
]

post_intro = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu massa eget massa maximus ultricies condimentum ut urna. Aenean imperdiet felis laoreet sem tristique, a tincidunt ligula egestas. Donec facilisis sodales mi. Morbi id feugiat lorem. Donec finibus luctus libero congue bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed aliquam urna id congue."
post_body = """<h2>Lorem ipsum dolor sit amet</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra lectus sed nulla scelerisque tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus faucibus, lectus ac pharetra dapibus, ipsum quam auctor neque, sit amet eleifend felis ipsum at odio. Nam dictum, massa vitae laoreet euismod, tortor tellus porta nibh, non laoreet tellus dui sed leo. Donec semper egestas sapien, in laoreet orci suscipit ut. Fusce molestie velit et sem vulputate accumsan. Pellentesque mattis velit risus, sed ornare ex commodo sit amet. In cursus orci vitae dignissim faucibus. Integer id convallis quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mollis dui in metus vulputate suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam convallis felis eu lectus placerat fermentum. Suspendisse et molestie odio. Duis quis ipsum lectus. Fusce nec sem at felis ullamcorper laoreet. Ut tempus augue eu ante lobortis sagittis. Curabitur id feugiat dolor. Suspendisse iaculis consequat lorem quis ullamcorper. Nunc sed magna ut urna sodales varius. Mauris posuere tempus placerat. Vestibulum ornare aliquet justo sit amet convallis. Nulla dignissim malesuada ligula. Quisque purus massa, fermentum et diam vel, lobortis sollicitudin nulla. Fusce iaculis lorem justo, non pharetra dolor aliquet vitae. Ut dictum tincidunt pretium. Duis vel dolor ut lorem vehicula maximus a at diam. Donec pharetra cursus dolor, a porta erat feugiat at. Aliquam venenatis ex elit, viverra pretium urna lobortis ut. Cras orci lorem, scelerisque nec rhoncus gravida, lobortis et elit. Morbi mollis auctor justo eu sollicitudin. Nulla dapibus ex non pharetra aliquet. Nam porta libero condimentum nisi euismod, quis dapibus mauris ultrices. Etiam diam purus, sodales ac ultricies aliquet, bibendum lobortis leo. Integer placerat auctor est, id consequat neque aliquet eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur porttitor mattis aliquet. Vestibulum vel augue justo. Donec eget sapien ipsum. Proin sed maximus elit. Vestibulum mi nunc, mollis eu sem nec, venenatis congue nunc. Aenean posuere feugiat porta.</p>

<h2>Consectetur adipiscing elit</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra lectus sed nulla scelerisque tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus faucibus, lectus ac pharetra dapibus, ipsum quam auctor neque, sit amet eleifend felis ipsum at odio. Nam dictum, massa vitae laoreet euismod, tortor tellus porta nibh, non laoreet tellus dui sed leo. Donec semper egestas sapien, in laoreet orci suscipit ut. Fusce molestie velit et sem vulputate accumsan. Pellentesque mattis velit risus, sed ornare ex commodo sit amet. In cursus orci vitae dignissim faucibus. Integer id convallis quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mollis dui in metus vulputate suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam convallis felis eu lectus placerat fermentum. Suspendisse et molestie odio. Duis quis ipsum lectus. Fusce nec sem at felis ullamcorper laoreet. Ut tempus augue eu ante lobortis sagittis. Curabitur id feugiat dolor. Suspendisse iaculis consequat lorem quis ullamcorper. Nunc sed magna ut urna sodales varius. Mauris posuere tempus placerat. Vestibulum ornare aliquet justo sit amet convallis. Nulla dignissim malesuada ligula. Quisque purus massa, fermentum et diam vel, lobortis sollicitudin nulla. Fusce iaculis lorem justo, non pharetra dolor aliquet vitae. Ut dictum tincidunt pretium. Duis vel dolor ut lorem vehicula maximus a at diam. Donec pharetra cursus dolor, a porta erat feugiat at. Aliquam venenatis ex elit, viverra pretium urna lobortis ut. Cras orci lorem, scelerisque nec rhoncus gravida, lobortis et elit. Morbi mollis auctor justo eu sollicitudin. Nulla dapibus ex non pharetra aliquet. Nam porta libero condimentum nisi euismod, quis dapibus mauris ultrices. Etiam diam purus, sodales ac ultricies aliquet, bibendum lobortis leo. Integer placerat auctor est, id consequat neque aliquet eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur porttitor mattis aliquet. Vestibulum vel augue justo. Donec eget sapien ipsum. Proin sed maximus elit. Vestibulum mi nunc, mollis eu sem nec, venenatis congue nunc. Aenean posuere feugiat porta.</p>

<h2>Ed do eiusmod tempor incididunt ut labore et dolore magna aliqua</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra lectus sed nulla scelerisque tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus faucibus, lectus ac pharetra dapibus, ipsum quam auctor neque, sit amet eleifend felis ipsum at odio. Nam dictum, massa vitae laoreet euismod, tortor tellus porta nibh, non laoreet tellus dui sed leo. Donec semper egestas sapien, in laoreet orci suscipit ut. Fusce molestie velit et sem vulputate accumsan. Pellentesque mattis velit risus, sed ornare ex commodo sit amet. In cursus orci vitae dignissim faucibus. Integer id convallis quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mollis dui in metus vulputate suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam convallis felis eu lectus placerat fermentum. Suspendisse et molestie odio. Duis quis ipsum lectus. Fusce nec sem at felis ullamcorper laoreet. Ut tempus augue eu ante lobortis sagittis. Curabitur id feugiat dolor. Suspendisse iaculis consequat lorem quis ullamcorper. Nunc sed magna ut urna sodales varius. Mauris posuere tempus placerat. Vestibulum ornare aliquet justo sit amet convallis. Nulla dignissim malesuada ligula. Quisque purus massa, fermentum et diam vel, lobortis sollicitudin nulla. Fusce iaculis lorem justo, non pharetra dolor aliquet vitae. Ut dictum tincidunt pretium. Duis vel dolor ut lorem vehicula maximus a at diam. Donec pharetra cursus dolor, a porta erat feugiat at. Aliquam venenatis ex elit, viverra pretium urna lobortis ut. Cras orci lorem, scelerisque nec rhoncus gravida, lobortis et elit. Morbi mollis auctor justo eu sollicitudin. Nulla dapibus ex non pharetra aliquet. Nam porta libero condimentum nisi euismod, quis dapibus mauris ultrices. Etiam diam purus, sodales ac ultricies aliquet, bibendum lobortis leo. Integer placerat auctor est, id consequat neque aliquet eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur porttitor mattis aliquet. Vestibulum vel augue justo. Donec eget sapien ipsum. Proin sed maximus elit. Vestibulum mi nunc, mollis eu sem nec, venenatis congue nunc. Aenean posuere feugiat porta.</p>
"""
